<a href="https://colab.research.google.com/github/sunnysunil611/CodeAlpha_Attendance_Management_System/blob/main/Python_Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
new_arr = np.arange(10,100,5)
print(new_arr)

arr_1d = np.array([1,2,3,])
print(arr_1d)
print(arr_1d[1])


arr_2d = np.array([[1,2,3,],[7,8,9]], dtype=np.float32)
print(arr_2d)
arr_2d.dtype


arr_3d =np.ones([2,3,4])
print(arr_3d)


arr_full = np.full((3,3), 100, dtype=np.float64)
print(arr_full)


[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[1 2 3]
2
[[1. 2. 3.]
 [7. 8. 9.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


In [ ]:
arr2d = np.array([[1,2,3],[4,5,6]])
ind=[[1,1],[0,0]]
s_e=arr2d[ind]
print(s_e)

[[[4 5 6]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]]]


In [ ]:
a=np.random.randint(1,10, size = 20)
print(a)

[7 3 3 7 5 5 9 6 3 6 4 1 9 1 9 9 5 2 8 7]
